name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Stáhne kód
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Node
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) Instalace
      - name: Install dependencies
        run: npm install

      # 4) Build
      - name: Build
        run: npm run build

      # 5) Pages setup
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 6) Upload
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4